# Build NodeJS Express app using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/javascript?view=vsts

queue: 'Hosted Linux Preview'

steps:
- script: |
    npm install
#    npm test
- script: gulp

- task: PublishTestResults@2
  inputs:
#    testRunner: JUnit my change
    testResultsFiles: '**/test-results.xml' #my change
    testRunTitle: 'Test results for JavaScript' #my change

#my change
- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
